// Code generated by CodeGenerator. Not generate if exist
//
// Source: account.proto
// Time: 2022-12-11 15:29:06

package logic

import (
    "ProjectX/service/account/internal/svc"
    "ProjectX/service/account/pb/account"
    "context"

    "github.com/zeromicro/go-zero/core/logx"
)

type GetOrCreateAccountLogic struct {
	ctx         context.Context
	svcCtx      *svc.ServiceContext
	logx.Logger // TODO: 需要替换为 library
}

func NewGetOrCreateAccountLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GetOrCreateAccountLogic {
	return &GetOrCreateAccountLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}

func (l *GetOrCreateAccountLogic) GetOrCreateAccount(in *account.GetOrCreateAccountRequest) (*account.GetOrCreateAccountResponse, error) {
	// TODO: logic write here

	return &account.GetOrCreateAccountResponse{}, nil
}
