// Code generated by CodeGenerator. Not generate if exist
//
// Source: gate.proto
// Time: 2023-06-20 10:50:20

package svc

import "ProjectX/access/gate/internal/config"

type ServiceContext struct {
	Config config.Config
}

func NewServiceContext(c config.Config) *ServiceContext {
	// TODO: 连接数据库，创建协程，设置缓冲等
	return &ServiceContext{
		Config: c,
	}
}
