// Code generated by CodeGenerator. Not generate if exist
//
// Source: account.proto
// Time: 2022-12-11 15:29:06

package consts

import "fmt"

var (
	ErrInvalidArgument = fmt.Errorf("invalid argument")
)
