// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: game.proto
// Time: 2023-07-25 10:14:49

package define

import (
	"ProjectX/access/game/pb/game"

	"context"
	"google.golang.org/grpc"
)

type (
	Action = game.Action
	SetGameEnvironmentRequest = game.SetGameEnvironmentRequest
	SetGameEnvironmentResponse = game.SetGameEnvironmentResponse

	Game interface {
		SetGameEnvironment(ctx context.Context, in *SetGameEnvironmentRequest) (*SetGameEnvironmentResponse, error)
	}

	Listener interface { // 当前服务的监听
		// Start 开启监听
		Start()
		// Stop 关闭监听
		Stop()
		// RegisterService 向 grpc 注册监听，protobuf 生成的 rpc 需要
		RegisterService(desc *grpc.ServiceDesc, impl interface{})
	}
)
