// Code generated by CodeGenerator. Not generate if exist
//
// Source: gate.proto
// Time: 2023-06-20 10:50:20

package config

type RpcServerBaseConfig struct {
	ListenOn string
	RpcMode  string `json:",default=grpc,options=grpc|rabbit|inter"`
}

type Config struct {
	RpcServerBaseConfig
	Spec gateSpecialConfig
}

type gateSpecialConfig struct {
}
