// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: account.proto
// Time: 2023-05-25 17:18:07

package server

import (
	"context"

    "ProjectX/service/account/internal/logic"
	"ProjectX/service/account/internal/svc"
	"ProjectX/service/account/pb/account"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
	account.UnimplementedAccountServer
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) GetOrCreateAccount(ctx context.Context, in *account.GetOrCreateAccountRequest) (*account.GetOrCreateAccountResponse, error) {
	l := logic.NewGetOrCreateAccountLogic(ctx, s.svcCtx)
	return l.GetOrCreateAccount(in)
}
