// Code generated by CodeGenerator. Not generate if exist
//
// Source: account.proto
// Time: 2022-12-11 15:29:06

package main

import (
	"ProjectX/base"
	"ProjectX/service/account/consts"
	"ProjectX/service/account/internal/config"
	"ProjectX/service/account/internal/server"
	"ProjectX/service/account/internal/svc"
	"ProjectX/service/account/pb/account"
	"ProjectX/service/account/rpc"
	"flag"

	"github.com/zeromicro/go-zero/core/conf"
)

var configFile = flag.String("f", base.GetConfigFilePathByService(consts.SvcName), "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)

	s := rpc.NewListener(ctx)
	account.RegisterAccountServer(s, server.NewAccountServer(ctx))
	defer s.Stop()
	s.Start()
}
