// Code generated by CodeGenerator. Not generate if exist
//
// Source: matchmaking.proto
// Time: 2023-07-05 10:20:01

package main

import (
	"ProjectX/base"
	"ProjectX/service/matchmaking/consts"
	"ProjectX/service/matchmaking/internal/config"
	"ProjectX/service/matchmaking/internal/server"
	"ProjectX/service/matchmaking/internal/svc"
	"ProjectX/service/matchmaking/pb/matchmaking"
	"ProjectX/service/matchmaking/rpc"
	"flag"

	"github.com/zeromicro/go-zero/core/conf"
)

var configFile = flag.String("f", base.GetConfigFilePathByService(consts.SvcName), "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)

	s := rpc.NewListener(ctx)
	matchmaking.RegisterMatchmakingServer(s, server.NewMatchmakingServer(ctx))
	defer s.Stop()
	s.Start()
}
