// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: account.proto
// Time: 2023-05-25 17:18:07

package grpc

import (
	"ProjectX/service/account/pb/account"
	"ProjectX/service/account/rpc/define"

	"context"
	"google.golang.org/grpc"
)

type grpcAccount struct {
	client *grpc.ClientConn
}

func getAddress() string {
	return "127.0.0.1:6200" // TODO: 使用 etcd 查询 "rpc.account"，获取连接地址
}

func NewGrpcAccount() define.Account {
	client, err := grpc.Dial(getAddress())
	if err != nil {
		return nil
	}
	return &grpcAccount{
		client: client,
	}
}

func (r *grpcAccount) GetOrCreateAccount(ctx context.Context, in *define.GetOrCreateAccountRequest) (*define.GetOrCreateAccountResponse, error) {
	client := account.NewAccountClient(r.client)
	return client.GetOrCreateAccount(ctx, in)
}
