// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: game.proto
// Time: 2023-07-25 10:14:49

package grpc

import (
	"ProjectX/access/game/pb/game"
	"ProjectX/access/game/rpc/define"

	"context"
	"google.golang.org/grpc"
)

type grpcGame struct {
	client *grpc.ClientConn
}

func getAddress() string {
	return "127.0.0.1:6200" // TODO: 使用 etcd 查询 "rpc.account"，获取连接地址
}

func NewGrpcGame() define.Game {
	client, err := grpc.Dial(getAddress())
	if err != nil {
		return nil
	}
	return &grpcGame{
		client: client,
	}
}

func (r *grpcGame) SetGameEnvironment(ctx context.Context, in *define.SetGameEnvironmentRequest) (*define.SetGameEnvironmentResponse, error) {
	client := game.NewGameClient(r.client)
	return client.SetGameEnvironment(ctx, in)
}
