// Code generated by CodeGenerator. Not generate if exist
//
// Source: game.proto
// Time: 2023-07-25 08:25:21

package main

import (
	"ProjectX/access/game/consts"
	"ProjectX/access/game/internal/config"
	"ProjectX/access/game/internal/server"
	"ProjectX/access/game/internal/svc"
	"ProjectX/access/game/pb/game"
	"ProjectX/access/game/rpc"
	"ProjectX/base"
	"ProjectX/library/network"
	"flag"

	"github.com/zeromicro/go-zero/core/conf"
)

var configFile = flag.String("f", base.GetConfigFilePathByService(consts.SvcName), "the config file")

func main() {
	flag.Parse()

	var c config.Config
	conf.MustLoad(*configFile, &c)
	ctx := svc.NewServiceContext(c)

	s := rpc.NewListener(ctx)
	game.RegisterGameServer(s, server.NewGameServer(ctx))
	defer s.Stop()
	defer network.DestroyAll()
	s.Start()
}
