// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOrCreateAccountRequest struct {
	// 用户账号 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户账号密码
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrCreateAccountRequest) Reset()         { *m = GetOrCreateAccountRequest{} }
func (m *GetOrCreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetOrCreateAccountRequest) ProtoMessage()    {}
func (*GetOrCreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *GetOrCreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrCreateAccountRequest.Unmarshal(m, b)
}
func (m *GetOrCreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrCreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetOrCreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrCreateAccountRequest.Merge(m, src)
}
func (m *GetOrCreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetOrCreateAccountRequest.Size(m)
}
func (m *GetOrCreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrCreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrCreateAccountRequest proto.InternalMessageInfo

func (m *GetOrCreateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrCreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AccountInfo struct {
	// 昵称   此处用作示例，实际场景按需求添加字段
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}
func (*AccountInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *AccountInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountInfo.Unmarshal(m, b)
}
func (m *AccountInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountInfo.Marshal(b, m, deterministic)
}
func (m *AccountInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountInfo.Merge(m, src)
}
func (m *AccountInfo) XXX_Size() int {
	return xxx_messageInfo_AccountInfo.Size(m)
}
func (m *AccountInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountInfo proto.InternalMessageInfo

func (m *AccountInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type GetOrCreateAccountResponse struct {
	// 错误码
	ErrorCode uint32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	// 是否是新创建的账号
	IsCreated bool `protobuf:"varint,2,opt,name=isCreated,proto3" json:"isCreated,omitempty"`
	// 账号具体信息
	Account              *AccountInfo `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetOrCreateAccountResponse) Reset()         { *m = GetOrCreateAccountResponse{} }
func (m *GetOrCreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetOrCreateAccountResponse) ProtoMessage()    {}
func (*GetOrCreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *GetOrCreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrCreateAccountResponse.Unmarshal(m, b)
}
func (m *GetOrCreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrCreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetOrCreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrCreateAccountResponse.Merge(m, src)
}
func (m *GetOrCreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetOrCreateAccountResponse.Size(m)
}
func (m *GetOrCreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrCreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrCreateAccountResponse proto.InternalMessageInfo

func (m *GetOrCreateAccountResponse) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *GetOrCreateAccountResponse) GetIsCreated() bool {
	if m != nil {
		return m.IsCreated
	}
	return false
}

func (m *GetOrCreateAccountResponse) GetAccount() *AccountInfo {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*GetOrCreateAccountRequest)(nil), "account.GetOrCreateAccountRequest")
	proto.RegisterType((*AccountInfo)(nil), "account.AccountInfo")
	proto.RegisterType((*GetOrCreateAccountResponse)(nil), "account.GetOrCreateAccountResponse")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xdc, 0xb9,
	0x24, 0xdd, 0x53, 0x4b, 0xfc, 0x8b, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x1d, 0x21, 0xa2, 0x41,
	0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c,
	0x1a, 0x9c, 0x41, 0x4c, 0x99, 0x29, 0x42, 0x52, 0x5c, 0x1c, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9,
	0x45, 0x29, 0x12, 0x4c, 0x60, 0x51, 0x38, 0x5f, 0x49, 0x93, 0x8b, 0x1b, 0xaa, 0xdb, 0x33, 0x2f,
	0x2d, 0x1f, 0xa4, 0x34, 0x2f, 0x33, 0x39, 0x3b, 0x2f, 0x31, 0x37, 0x15, 0x6a, 0x00, 0x9c, 0xaf,
	0xd4, 0xc1, 0xc8, 0x25, 0x85, 0xcd, 0xd2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x19, 0x2e,
	0xce, 0xd4, 0xa2, 0xa2, 0xfc, 0x22, 0xe7, 0xfc, 0x14, 0x88, 0x5e, 0xde, 0x20, 0x84, 0x00, 0x48,
	0x36, 0xb3, 0x18, 0xa2, 0x11, 0xe2, 0x08, 0x8e, 0x20, 0x84, 0x80, 0x90, 0x1e, 0x17, 0xcc, 0x67,
	0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a, 0x30, 0x8f, 0x23, 0xb9, 0x2e, 0x08, 0xa6,
	0xc8, 0x28, 0x83, 0x8b, 0x1d, 0x2a, 0x2e, 0x14, 0xcb, 0x25, 0x94, 0x8e, 0xe1, 0x28, 0x21, 0x25,
	0xb8, 0x7e, 0x9c, 0xc1, 0x24, 0xa5, 0x8c, 0x57, 0x0d, 0xc4, 0x57, 0x4e, 0xdc, 0x51, 0x9c, 0x7a,
	0xfa, 0x50, 0x75, 0x49, 0x6c, 0xe0, 0x58, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xbd,
	0x9e, 0x3a, 0x96, 0x01, 0x00, 0x00,
}
