// Code generated by CodeGenerator. Not generate if exist
//
// Source: game.proto
// Time: 2023-07-25 08:25:21

package config

type RpcServerBaseConfig struct {
	ListenOn string
	RpcMode  string `json:",default=grpc,options=grpc|rabbit|inter"`
}

type Config struct {
	RpcServerBaseConfig
	Spec gameSpecialConfig
}

type gameSpecialConfig struct {
	GameSessionNum int `json:",default=8"`
}
