// Code generated by CodeGenerator. Not generate if exist
//
// Source: gate.proto
// Time: 2023-06-20 10:50:20

package logic

import (
	"ProjectX/access/gate/internal/agent"
	"ProjectX/access/gate/internal/svc"
	"ProjectX/access/gate/pb/gate"
	"ProjectX/library/log"
	"context"
)

type GetUserNumberLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	log.Logger
}

func NewGetUserNumberLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GetUserNumberLogic {
	return &GetUserNumberLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: log.WithContext(ctx),
	}
}

func (l *GetUserNumberLogic) GetUserNumber(_ *gate.GetUserNumberRequest) (*gate.GetUserNumberResponse, error) {
	return &gate.GetUserNumberResponse{
		Number: int32(agent.GetUserNum()),
	}, nil
}
