// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: gate.proto
// Time: 2023-06-20 10:56:47

package define

import (
	"ProjectX/access/gate/pb/gate"

	"context"
	"google.golang.org/grpc"
)

type (
	ClientRequest         = gate.ClientRequest
	ClientResponse        = gate.ClientResponse
	GetUserNumberRequest  = gate.GetUserNumberRequest
	GetUserNumberResponse = gate.GetUserNumberResponse

	Gate interface {
		GetUserNumber(ctx context.Context, in *GetUserNumberRequest) (*GetUserNumberResponse, error)
	}

	Listener interface { // 当前服务的监听
		// Start 开启监听
		Start()
		// Stop 关闭监听
		Stop()
		// RegisterService 向 grpc 注册监听，protobuf 生成的 rpc 需要
		RegisterService(desc *grpc.ServiceDesc, impl interface{})
	}
)
