#{If #{file.overwrite}}
// Code generated by CodeGenerator. DO NOT EDIT!
#{Else}
// Code generated by CodeGenerator. Not generate if exist
#{EndIf}
//
// Source: #{.package}.proto
// Time: #{DateTime}
