// Code generated by CodeGenerator. Not generate if exist
//
// Source: matchmaking.proto
// Time: 2023-07-05 10:20:01

package svc

import "ProjectX/service/matchmaking/internal/config"

type ServiceContext struct {
	Config config.Config
}

func NewServiceContext(c config.Config) *ServiceContext {
	// TODO: 连接数据库，创建协程，设置缓冲等
	return &ServiceContext{
		Config: c,
	}
}
