// Code generated by CodeGenerator. Not generate if exist
//
// Source: matchmaking.proto
// Time: 2023-07-05 10:20:01

package logic

import (
    "ProjectX/library/log"
    "ProjectX/service/matchmaking/internal/svc"
    "ProjectX/service/matchmaking/pb/matchmaking"
    "context"
)

type ResultLogic struct {
	ctx         context.Context
	svcCtx      *svc.ServiceContext
	log.Logger
}

func NewResultLogic(ctx context.Context, svcCtx *svc.ServiceContext) *ResultLogic {
	return &ResultLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: log.WithContext(ctx),
	}
}

func (l *ResultLogic) Result(in *matchmaking.ResultRequest) (*matchmaking.ResultResponse, error) {
	// TODO: logic write here

	return &matchmaking.ResultResponse{}, nil
}
