// Code generated by CodeGenerator. Not generate if exist
//
// Source: matchmaking.proto
// Time: 2023-07-05 10:20:01

package svc

import (
	"ProjectX/service/matchmaking/internal/config"
	"ProjectX/service/matchmaking/internal/pool"
)

type ServiceContext struct {
	Config config.Config
	Pool   *pool.Pool
}

func NewServiceContext(c config.Config) *ServiceContext {
	return &ServiceContext{
		Config: c,
		Pool:   pool.NewPool(),
	}
}
