// Code generated by CodeGenerator. Not generate if exist
//
// Source: account.proto
// Time: 2022-12-11 15:29:06

package logic

import (
	"ProjectX/library/log"
	"ProjectX/service/account/consts"
	"ProjectX/service/account/internal/svc"
	"ProjectX/service/account/pb/account"
	"context"
)

type GetOrCreateAccountLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	log.Logger
}

func NewGetOrCreateAccountLogic(ctx context.Context, svcCtx *svc.ServiceContext) *GetOrCreateAccountLogic {
	return &GetOrCreateAccountLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: log.WithContext(ctx),
	}
}

func (l *GetOrCreateAccountLogic) GetOrCreateAccount(in *account.GetOrCreateAccountRequest) (*account.GetOrCreateAccountResponse, error) {
	if in == nil || in.Id == "" || in.Platform == "" {
		return nil, consts.ErrInvalidArgument
	}

	return &account.GetOrCreateAccountResponse{}, nil
}
