// Code generated by CodeGenerator. DO NOT EDIT!
//
// Source: gate.proto
// Time: 2023-06-20 10:56:47

package grpc

import (
	"ProjectX/access/gate/pb/gate"
	"ProjectX/access/gate/rpc/define"

	"context"
	"google.golang.org/grpc"
)

type grpcGate struct {
	client *grpc.ClientConn
}

func getAddress() string {
	return "127.0.0.1:6200" // TODO: 使用 etcd 查询 "rpc.account"，获取连接地址
}

func NewGrpcGate() define.Gate {
	client, err := grpc.Dial(getAddress())
	if err != nil {
		return nil
	}
	return &grpcGate{
		client: client,
	}
}

func (r *grpcGate) GetUserNumber(ctx context.Context, in *define.GetUserNumberRequest) (*define.GetUserNumberResponse, error) {
	client := gate.NewGateClient(r.client)
	return client.GetUserNumber(ctx, in)
}
